### ISSUE TITLE
check with RefactorU about printing cards

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/ndoch2016#27]

**Comment by raemacias** [comment]
RefactorU will not be able to print the cards for this event, so we need to find someone else to do it.

**Comment by karenderrickdavis** [comment]
Ok. Not sure we need to.  What do you think?  Maybe CA will, if we think we
really need some.
Karen

**Comment by raemacias** [comment]
I don't think they are all that necessary, but anyone else can chime in on that as well.

**Comment by raemacias** [comment]
CfD will pay to have the cards. We will have 500-1000 printed. Dave will print them.
