### ISSUE TITLE
followup with RefactorU regarding financial support for food

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/ndoch2016#29]

**Comment by raemacias** [comment]
RefactorU will sponsor $500 for food. We need to provide to them an invoice from CfD and they will pay us.

**Comment by karenderrickdavis** [comment]
Awesome!

**Comment by karenderrickdavis** [comment]
I sent Pattie an email with details about how to give us the money through Code for America (check or wire). SInce it is so close to the date of the event, we will most likely have to spend the money from our current funds and then have RefactorU donate the correct amount to Code for America (remember to add 10% to cover the amount Code for America will take).
