### ISSUE TITLE
Recruit Stakeholders

### ISSUE THREAD

**Issue by karenderrickdavis** [codefordenver/ndoch2016#4]
### Recruit Stakeholders

Now that we've decided what problem(s) to focus on (#1), it's time to recruit stakeholders and SME's to help us better understand the problem context. 
- [ ] Find and recruit 2-3 subject matter experts who deal with your problem context on a daily basis
- [ ] Invite these SME's to be a part of crafting problem statements in advance or adding context to your problem set
- [ ] Invite SME's to participate in the event, either through speaking, joining teams, judging, or giving feedback

**Comment by karenderrickdavis** [comment]
Mile High Connects Mtg
9-5, FRESC
Denver Homeless Out Loud (Terese Henry)
Office of Strategic Partnerships (Miriam Pena)
City Office that deals with housing.

**Comment by karenderrickdavis** [comment]
spoke with Gary Community Investments about their data and potential challenges.  One possible project:  develop a resource for homeowners to calculate the "true profit" of selling their home when "predatory buyers" come knocking at the door.  AND chk the current market for what they could buy with the profit.

**Comment by Mira321** [comment]
Just spoke with Kim Easton from Urban Peak - http://www.urbanpeak.org  (homeless youth)  She is the Exec Dir - listened to my pitch and was interested.  She is attending the Mayors Summit on Housing at DU TOMORROW (Thursday). I am sending her info and she is getting back to me.  I think there is a good chance she could be one of our speaker/educators on the issue - she or someone from urbanpeak.   - Posted about this on the NDoCH Flow Doc too... still learning where these things go...

**Comment by Mira321** [comment]
LM and sent email to Luis Linares - program manager for Metro Caring
llinares@metrocaring.org   720-343-8452
http://www.metrocaring.org/who/team.html

Tried to reach Fresc again but was not successful.

**Comment by Mira321** [comment]
Karen - your phone & email info is missing on the info sheet and doc for stakeholders.  As I am sending this out - and will be gone starting tomorrow through next Tues it would be great if I can put that info in the email and on the doc - if you are ok with that.

**Comment by Mira321** [comment]
Karen - apologies - I see it now - had the wrong doc. :-o

**Comment by Mira321** [comment]
I just uploaded to the NDoCH 2016 folder a template in a word doc that can be used for recruiting Stakeholders/Subject Matter Experts - now or in the future.  You can drop the text into an email or print as needed. Change it as you see fit.  It's called Hello Stakeholder!Template
Here it is also
[Hello Stakeholder! Template.docx](https://github.com/codefordenver/ndoch2016/files/273310/Hello.Stakeholder.Template.docx)

**Comment by Mira321** [comment]
Tried Fresc again - they just don't seem to be answering their phone.  So I sent a Hello Stakeholder! email to the executive director and LM for Felicia and CC'd their office manager:  
Felicia Griffin  
fgriffin@fresc.org
303.936.0503 x 100
and 
Lorrine Banzie  | Office Manager
lbanzie@fresc.org
303.936.0503 x 107

**Comment by Mira321** [comment]
ONE SUBJECT MATTER EXPERT ON BOARD!  Just heard back from Luis Linares at Metro Caring - he is willing to be a Subject Matter expert for NCoCH and is willing to stay the whole morning.  I told him I was going out of town and would contact him again next week.  If we get other parties interested in being a subject matter expert/stake holder, then we may need to address that issue and figure out how to keep them interested and engaged beyond NDoCH.  Woo Hoo!!
