### ISSUE TITLE
Create E-mail Template

### ISSUE THREAD

**Issue by raemacias** [codefordenver/ndoch2016#43]
Create a basic e-mail template for e-mail campaign with basic images and text

**Comment by Mira321** [comment]
Hello -
I am a member of Code for Denver and I wanted to invite you to a FREE event
we think you might be interested in.  Please see the information below and
visit the links.  You do not need to be a programmer for this event.  It is
a great way to learn about how programming can be used to benefit the
community.  We would love to see you there!

Code for Denver is a Non-Profit organization and part of Code for
America.

_National Day of Civic Hacking - with Code for Denver_
_On Saturday June 4, 2016_, thousands of people  across the nation will
join together for National Day of Civic Hacking events. The goal of the
organization is to collaborate with residents, community groups,
non-profits, socially minded business people and government to make their
communities stronger by providing computer programming expertise and
support.

Join us for Denver's celebration of National Day of Civic Hacking as we
focus on _housing challenges_. Most everyone is talking about the housing
challenges in Denver.  It is time to put our heads and hearts together to
create some solutions.

*All *skills levels of expertise welcome, including students!  Non
programmers also invited.  Come learn and contribute to this dynamic
creative effort in community problem solving!
http://www.meetup.com/CodeForDenver/events/230650372/
http://www.codefordenver.org/

[image: Inline image 1]

**Comment by raemacias** [comment]
Looks good so far...I'll have a better look at it when I get home later. I can't make it to CfD tonight, unfortunately, everything ran late for me today.
Rae

Date: Mon, 16 May 2016 15:59:47 -0700

**Comment by switzersc** [comment]
Good start! I would update it to start with the paragraph beginning "Join us for Denver's celebration...", then the "National Day of Civic Hacking" details paragraph, then the one liner about CfD being a nonprofit. This is my revision:

Join us for Denver's celebration of National Day of Civic Hacking on Saturday, June 4, as we focus on _housing challenges_. Most everyone is talking about the housing challenges in Denver. It is time to put our heads and hearts together to create solutions that can have an impact. 

The _National Day of Civic Hacking_ in Denver is a FREE event that is part of a larger national movement. Thousands of people across the country will join together to collaborate with residents, community groups, non-profits, socially minded business people and government to make their communities stronger through building civic-oriented technology and using government data.

_All_ skills levels of expertise welcome, including students! No technical skills required! Come learn and contribute to this dynamic creative effort in community problem solving! http://www.meetup.com/CodeForDenver/events/230650372/ http://www.codefordenver.org/

Code for Denver is a Non-Profit organization and part of Code for America.

**Comment by Mira321** [comment]
OK - so here is another version that includes all the URL's that I think we have for RSVP, registration and more info

Join us for Denver's celebration of  the National Day of Civic Hacking!!

Saturday, June 4, Code for Denver is participating the Code for America's National Day of Civic Hacking as we focus on housing challenges. Most everyone is talking about the housing challenges in Denver. It is time to put our heads, hearts and coding fingers together to create solutions that can have an impact!

The National Day of Civic Hacking in Denver is a FREE event that is part of a larger national movement. Thousands of people across the country will join together to collaborate with residents, community groups, non-profits, socially minded business people and government to make their communities stronger through building civic-oriented technology and using data to address current issues.

All skills levels of expertise are welcome, including students! No technical skills required! Come learn and contribute to this dynamic creative effort in community problem solving!  For more information or to register, visit these links below.  If you have specific knowledge of the housing issues and can help identify specific projects that Code for Denver can work on, or know someone who does, please contact us!

http://www.meetup.com/CodeForDenver/events/230650372/

http://www.codefordenver.org/

https://www.eventbrite.com/e/national-day-of-civic-hacking-tickets-25497324183

https://www.facebook.com/events/1150990984941445/

Code for Denver is a Non-Profit organization and part of Code for America.

<<< INSERT POST CARD HERE>>>>

Here is the agenda: 

Hacking for Housing Solutions

AGENDA

8:00  Breakfast

8:15  Welcome

8:30 Education on the issue and challenge spaces

9:00 Q & A

9:30 Hacking: Break into groups according to challenges

12:00 Lunch and check in 

12:45 More hacking

4:00 Report out

4:30 Next steps toward implementation

5:00 Adjourn

5:00 - 10:00 After event hack-a-thon. More hacking for those who just can't stop!!!!
